import Footer from '@Components/Footer'
import { Navbar } from '@Components/Navbar'
import '@styles/globals.css'
// import { Inter } from 'next/font/google'

// const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet"href="https://fonts.googleapis.com/css?family=Dancing+Script"/>
        <link rel="stylesheet"href="https://fonts.googleapis.com/css?family=Courgette"/>
      </head>
      <body className=''>
        <Navbar/>
        {children}
        <Footer/>
      </body>
    </html>
  )
}
