// 'use client';
import FloatingBar from '@Components/FloatingBar'
import Footer from '@Components/Footer'
import { Navbar } from '@Components/Navbar'
import Tos from '@Components/Tos'
import '@styles/globals.css'
// import { useState } from 'react'
// import { Inter } from 'next/font/google'

// const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  // const [showTos, setshowTos] = useState(false)
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet"href="https://fonts.googleapis.com/css?family=Dancing+Script"/>
        <link rel="stylesheet"href="https://fonts.googleapis.com/css?family=Courgette"/>
      </head>
      <body className=''>
        <Navbar/>
        <FloatingBar></FloatingBar>
        {/* <Tos 
         show={showTos} setshow={setshowTos}
        /> */}
        {children}

        <Footer 
        // setshow={setshowTos}
        />
      </body>
    </html>
  )
}
